# Generated by Django 4.1.5 on 2023-01-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArquivoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=1)),
                ("data", models.DateField()),
                ("valor", models.FloatField()),
                ("cpf", models.IntegerField()),
                ("cartao", models.CharField(max_length=12)),
                ("hora", models.TimeField()),
                ("dono_da_loja", models.CharField(max_length=14)),
                ("nome_da_loja", models.CharField(max_length=19)),
            ],
        ),
        migrations.CreateModel(
            name="FileForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="")),
            ],
        ),
    ]
